// src/data/planetParameters.ts

export const planetParameters = {
  basic: [
    {
      name: "Orbital Period",
      unit: "days",
      description: "Time the planet takes to complete one full orbit around its host star. Shorter periods indicate planets closer to their star.",
      min: 0,
      max: 500,
    },
    {
      name: "Planet Radius",
      unit: "Earth radii",
      description: "The size of the planet compared to Earth. A radius of 1 means the planet is the same size as Earth.",
      min: 0,
      max: 20,
    },
    {
      name: "Equilibrium Temperature",
      unit: "K",
      description: "The estimated temperature of the planet assuming no atmosphere, calculated based on its distance from the star and the star's brightness.",
      min: 200,
      max: 3000,
    },
    {
      name: "Insolation",
      unit: "Earth = 1",
      description: "Amount of energy the planet receives from its star compared to Earth. Higher values mean more stellar energy hits the planet.",
      min: 0,
      max: 500,
    },
    {
      name: "Stellar Effective Temperature",
      unit: "K",
      description: "The surface temperature of the planet's host star. Hotter stars emit more energy and can affect the planet's climate.",
      min: 2500,
      max: 10000,
    },
    {
      name: "Stellar Radius",
      unit: "Solar radii",
      description: "The size of the host star compared to the Sun. A larger star may produce more energy and heat the planet more.",
      min: null,
      max: null,
    },
  ],

  koi: [
    { name: "KOI FP Flag NT", description: "Flag indicating whether the planet candidate is a false positive based on the 'NT' detection method." },
    { name: "KOI FP Flag SS", description: "Flag indicating a potential false positive based on the 'SS' detection method." },
    { name: "KOI FP Flag CO", description: "Flag indicating a possible false positive from 'CO' analysis." },
    { name: "KOI FP Flag EC", description: "Flag for identifying false positives using the 'EC' method." },
    { name: "KOI Period Err1", description: "The uncertainty or upper error in measuring the planet's orbital period." },
    { name: "KOI Period Err2", description: "The uncertainty or lower error in measuring the planet's orbital period." },
    { name: "KOI Time0 BK", description: "The calculated mid-point time of the planet's transit across its star." },
    { name: "KOI Time0bk Err1", description: "The upper error margin for the mid-transit time." },
    { name: "KOI Time0bk Err2", description: "The lower error margin for the mid-transit time." },
    { name: "KOI Impact", description: "The distance between the center of the star and the path of the planet during transit, scaled so 0 is a central transit and 1 grazes the edge." },
    { name: "KOI Impact Err1", description: "Upper uncertainty for the impact parameter." },
    { name: "KOI Impact Err2", description: "Lower uncertainty for the impact parameter." },
    { name: "KOI Duration", description: "The total time the planet takes to pass in front of its star during transit, measured in hours." },
    { name: "KOI Duration Err1", description: "Upper error for transit duration." },
    { name: "KOI Duration Err2", description: "Lower error for transit duration." },
    { name: "KOI Depth", description: "The amount of light blocked by the planet during transit, measured in parts per million (ppm). Larger values indicate bigger planets or deeper transits." },
    { name: "KOI Depth Err1", description: "Upper uncertainty in transit depth measurement." },
    { name: "KOI Depth Err2", description: "Lower uncertainty in transit depth measurement." },
    { name: "KOI Planet Radius Err1", description: "Upper error in the measured radius of the planet." },
    { name: "KOI Planet Radius Err2", description: "Lower error in the measured radius of the planet." },
    { name: "KOI Equilibrium Temp Err1", description: "Upper uncertainty in the planet's equilibrium temperature." },
    { name: "KOI Equilibrium Temp Err2", description: "Lower uncertainty in the planet's equilibrium temperature." },
    { name: "KOI Insolation Err1", description: "Upper uncertainty in the insolation received by the planet." },
    { name: "KOI Insolation Err2", description: "Lower uncertainty in the insolation received by the planet." },
    { name: "KOI Model SNR", description: "Signal-to-noise ratio of the transit detection. Higher values indicate more reliable detections." },
    { name: "KOI TCE Planet Num", description: "The sequence number of the planet in the list of Threshold Crossing Events (TCEs)." },
    { name: "KOI Stellar Effective Temp Err1", description: "Upper uncertainty in the host star's effective temperature." },
    { name: "KOI Stellar Effective Temp Err2", description: "Lower uncertainty in the host star's effective temperature." },
    { name: "KOI Stellar Surface Gravity", description: "The logarithm of the star's surface gravity, which relates to its mass and size." },
    { name: "KOI Stellar Surface Gravity Err1", description: "Upper uncertainty in the star's surface gravity." },
    { name: "KOI Stellar Surface Gravity Err2", description: "Lower uncertainty in the star's surface gravity." },
    { name: "KOI Stellar Radius Err1", description: "Upper uncertainty in the radius of the star." },
    { name: "KOI Stellar Radius Err2", description: "Lower uncertainty in the radius of the star." },
    { name: "Right Ascension", description: "The celestial longitude of the star, used to locate it in the sky." },
    { name: "Declination", description: "The celestial latitude of the star, used to locate it in the sky." },
    { name: "KOI Kepler Magnitude", description: "Brightness of the star in the Kepler telescope's observation band; lower numbers mean brighter stars." },
  ],
};
