name: Frontend CI

on:
  push:
    paths:
      - 'exo-web/**'
  pull_request:
    paths:
      - 'exo-web/**'

defaults:
  run:
    working-directory: exo-web

jobs:
  checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ["1.1.34"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run tsc --noEmit

      - name: Build
        run: bun run build